#!/bin/bash

script=${0##*/}
_u() { cat << EOF
usage: $script HOST1 [ HOST2 .. HOSTn ]
This script syncs files via unison to hosts specified in $host_file
EOF
}

(( $# == 0 )) && { _u; exit 1; }

for host in "$@"; do
    output=$(unison -silent "$host" 2>&1)
    [[ $output ]] && { echo -e "$host\n$output"; } | logger -t unison -p user.warn
done

output=
output=$(unison -silent dtsteve-dm_test 2>&1)
[[ $output ]] && { echo -e "$host\n$output"; } | logger -t unison -p user.warn
ssh dtsteve -i /root/.ssh/id_rsa-syncbackup 'chown -R dm_test:dm_test /home/dm_test/'
